### ISSUE TITLE
Importing 'pub' BackgroundMaterials Resource from MainMenuPlugin causes RunTime Panic

### ISSUE THREAD

**Issue by anthonyarusso** [anthonyarusso/aeternum#1]
Error dump:
```
cargo run
   Compiling aeternum v0.1.0 (C:\Users\Anthony\code\rust\aeternum)
warning: field is never read: `hovered`
  --> src\custom_plugins\main_menu.rs:70:5
   |
70 |     hovered: Handle<ColorMaterial>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `pressed`
  --> src\custom_plugins\main_menu.rs:71:5
   |
71 |     pressed: Handle<ColorMaterial>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `button_system`
  --> src\custom_plugins\main_menu.rs:98:4
   |
98 | fn button_system (
   |    ^^^^^^^^^^^^^

warning: 3 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 4.74s
     Running `target\debug\aeternum.exe`
thread 'Compute Task Pool (2)' panicked at 'Resource does not exist aeternum::custom_plugins::main_menu::BackgroundMaterials.', C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\resource\resources.rs:282:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368:45
thread 'main' panicked at 'Task thread panicked while executing.: Any', C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.4.0\src\task_pool.rs:75:18
stack backtrace:
   0:     0x7ff7109ed579 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7109ed579 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7109ed579 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff7109ed579 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff710a04ebb - core::fmt::write
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\fmt\mod.rs:1080
   5:     0x7ff7109e9488 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\io\mod.rs:1516
   6:     0x7ff7109f0364 - std::sys_common::backtrace::_print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff7109f0364 - std::sys_common::backtrace::print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff7109f0364 - std::panicking::default_hook::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:208
   9:     0x7ff7109eff48 - std::panicking::default_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:227
  10:     0x7ff7109f0c1f - std::panicking::rust_panic_with_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:577
  11:     0x7ff7109f0785 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:484
  12:     0x7ff7109ede5f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff7109f0739 - std::panicking::begin_panic_handler
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
  14:     0x7ff710a02920 - core::panicking::panic_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
  15:     0x7ff710a02743 - core::option::expect_none_failed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\option.rs:1234
  16:     0x7ff71092b701 - core::result::Result<tuple<>, alloc::boxed::Box<Any>>::expect<tuple<>,alloc::boxed::Box<Any>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\result.rs:933
  17:     0x7ff710930072 - bevy_tasks::task_pool::{{impl}}::drop
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.4.0\src\task_pool.rs:73
  18:     0x7ff71092921f - core::ptr::drop_in_place<bevy_tasks::task_pool::TaskPoolInner>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  19:     0x7ff7108be172 - alloc::sync::Arc<bevy_tasks::task_pool::TaskPoolInner>::drop_slow<bevy_tasks::task_pool::TaskPoolInner>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\sync.rs:934
  20:     0x7ff7108bf7a5 - alloc::sync::{{impl}}::drop<bevy_tasks::task_pool::TaskPoolInner>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\sync.rs:1454
  21:     0x7ff710885d3e - core::ptr::drop_in_place<alloc::sync::Arc<bevy_tasks::task_pool::TaskPoolInner>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  22:     0x7ff7108853d3 - core::ptr::drop_in_place<bevy_tasks::task_pool::TaskPool>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  23:     0x7ff71088637e - core::ptr::drop_in_place<bevy_tasks::usages::ComputeTaskPool>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  24:     0x7ff710885cde - core::ptr::drop_in_place<core::cell::UnsafeCell<bevy_tasks::usages::ComputeTaskPool>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  25:     0x7ff710883bee - core::ptr::drop_in_place<bevy_ecs::resource::resources::StoredResource<bevy_tasks::usages::ComputeTaskPool>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  26:     0x7ff710884099 - core::ptr::drop_in_place<slice<bevy_ecs::resource::resources::StoredResource<bevy_tasks::usages::ComputeTaskPool>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  27:     0x7ff7108a45f4 - alloc::vec::{{impl}}::drop<bevy_ecs::resource::resources::StoredResource<bevy_tasks::usages::ComputeTaskPool>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\vec.rs:2636
  28:     0x7ff710883eff - core::ptr::drop_in_place<alloc::vec::Vec<bevy_ecs::resource::resources::StoredResource<bevy_tasks::usages::ComputeTaskPool>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  29:     0x7ff71088455e - core::ptr::drop_in_place<bevy_ecs::resource::resources::VecResourceStorage<bevy_tasks::usages::ComputeTaskPool>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  30:     0x7ff710884599 - core::ptr::drop_in_place<alloc::boxed::Box<ResourceStorage>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  31:     0x7ff710883cff - core::ptr::drop_in_place<bevy_ecs::resource::resources::ResourceData>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  32:     0x7ff7108844e5 - core::ptr::drop_in_place<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  33:     0x7ff7108ab28e - core::ptr::mut_ptr::{{impl}}::drop_in_place<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mut_ptr.rs:963
  34:     0x7ff7108d0cdd - hashbrown::raw::Bucket<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>::drop<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>
                               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.9.0\src\raw\mod.rs:334
  35:     0x7ff7108cd5bd - hashbrown::raw::{{impl}}::drop<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>
                               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.9.0\src\raw\mod.rs:1325
  36:     0x7ff710885cfe - core::ptr::drop_in_place<hashbrown::raw::RawTable<tuple<core::any::TypeId, bevy_ecs::resource::resources::ResourceData>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  37:     0x7ff710884045 - core::ptr::drop_in_place<hashbrown::map::HashMap<core::any::TypeId, bevy_ecs::resource::resources::ResourceData, ahash::random_state::RandomState>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  38:     0x7ff710883b4e - core::ptr::drop_in_place<std::collections::hash::map::HashMap<core::any::TypeId, bevy_ecs::resource::resources::ResourceData, ahash::random_state::RandomState>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  39:     0x7ff710869fbf - core::ptr::drop_in_place<bevy_ecs::resource::resources::Resources>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  40:     0x7ff710869c80 - core::ptr::drop_in_place<bevy_app::app::App>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  41:     0x7ff70f8ef4ae - core::ptr::drop_in_place<closure-1>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  42:     0x7ff70f8ee78e - core::ptr::drop_in_place<closure-0>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  43:     0x7ff70f954979 - core::ptr::drop_in_place<alloc::boxed::Box<FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ptr\mod.rs:175
  44:     0x7ff70f95abdc - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:252
  45:     0x7ff8dfc71030 - <unknown>
  46:     0x7ff8dfc74a52 - is_exception_typeof
  47:     0x7ff8dfc7e7a4 - _C_specific_handler
  48:     0x7ff8dfc73cc8 - is_exception_typeof
  49:     0x7ff8dfc7f0d1 - _CxxFrameHandler3
  50:     0x7ff8f945138f - _chkstk
  51:     0x7ff8f93d1d19 - RtlUnwindEx
  52:     0x7ff8dfc7ec62 - _C_specific_handler
  53:     0x7ff8dfc72955 - is_exception_typeof
  54:     0x7ff8dfc72d81 - is_exception_typeof
  55:     0x7ff8dfc73dc4 - is_exception_typeof
  56:     0x7ff8dfc7f0d1 - _CxxFrameHandler3
  57:     0x7ff8f945130f - _chkstk
  58:     0x7ff8f93fb5e4 - RtlRaiseException
  59:     0x7ff8f93fb335 - RtlRaiseException
  60:     0x7ff8f6ead759 - RaiseException
  61:     0x7ff8dfc76220 - CxxThrowException
  62:     0x7ff7109f69d1 - panic_unwind::real_imp::panic
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\panic_unwind\src\seh.rs:315
  63:     0x7ff7109f6959 - panic_unwind::__rust_start_panic
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\panic_unwind\src\lib.rs:112
  64:     0x7ff7109f0e38 - std::panicking::rust_panic
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:626
  65:     0x7ff7109f0cd6 - std::panicking::rust_panic_with_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:596
  66:     0x7ff7109f0785 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:484
  67:     0x7ff7109ede5f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:153
  68:     0x7ff7109f0739 - std::panicking::begin_panic_handler
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
  69:     0x7ff710a02920 - core::panicking::panic_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
  70:     0x7ff710a026a2 - core::option::expect_failed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\option.rs:1226
  71:     0x7ff71089bade - core::option::Option::expect<tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\option.rs:346
  72:     0x7ff7108b6f73 - async_task::task::{{impl}}::poll<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\task.rs:368
  73:     0x7ff7108b0924 - bevy_tasks::task_pool::{{impl}}::scope::{{closure}}<closure-0,tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.4.0\src\task_pool.rs:185
  74:     0x7ff710880a4a - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\mod.rs:80
  75:     0x7ff71088080d - core::future::future::{{impl}}::poll<mut Future*>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\future.rs:119
  76:     0x7ff71087e5a6 - async_executor::{{impl}}::spawn::{{closure}}<alloc::vec::Vec<tuple<>>,core::pin::Pin<mut Future*>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:138
  77:     0x7ff710880b7a - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\future\mod.rs:80
  78:     0x7ff7108fd92b - async_task::raw::RawTask<core::future::from_generator::GenFuture<generator-0>, alloc::vec::Vec<tuple<>>, closure-0>::run<core::future::from_generator::GenFuture<generator-0>,alloc::vec::Vec<tuple<>>,closure-0>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\raw.rs:489
  79:     0x7ff71094faee - async_task::runnable::Runnable::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\runnable.rs:309
  80:     0x7ff71093b493 - async_executor::Executor::try_tick
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:175
  81:     0x7ff7108b0615 - bevy_tasks::task_pool::TaskPool::scope<closure-0,tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.4.0\src\task_pool.rs:212
  82:     0x7ff7108cab14 - bevy_ecs::schedule::stage_executor::ParallelSystemStageExecutor::run_systems
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\stage_executor.rs:300
  83:     0x7ff7108cc219 - bevy_ecs::schedule::stage_executor::{{impl}}::execute_stage
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\stage_executor.rs:450
  84:     0x7ff7108bb145 - bevy_ecs::schedule::stage::SystemStage::run_once
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\stage.rs:102
  85:     0x7ff7108bb4a5 - bevy_ecs::schedule::stage::{{impl}}::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\stage.rs:136
  86:     0x7ff7108bff0d - bevy_ecs::schedule::Schedule::run_once
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\mod.rs:149
  87:     0x7ff7108c0285 - bevy_ecs::schedule::{{impl}}::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\mod.rs:189
  88:     0x7ff7108bff0d - bevy_ecs::schedule::Schedule::run_once
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\mod.rs:149
  89:     0x7ff7108c0285 - bevy_ecs::schedule::{{impl}}::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\mod.rs:189
  90:     0x7ff7108bff5b - bevy_ecs::schedule::Schedule::initialize_and_run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.4.0\src\schedule\mod.rs:156
  91:     0x7ff71086bf7e - bevy_app::app::App::update
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.4.0\src\app.rs:56
  92:     0x7ff70f8cfeaa - bevy_winit::winit_runner::{{closure}}
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.4.0\src\lib.rs:371
  93:     0x7ff70f91ab48 - winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-1>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:203
  94:     0x7ff70f94b753 - alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\boxed.rs:1049
  95:     0x7ff70f95aa6b - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:245
  96:     0x7ff70f956db6 - std::panic::{{impl}}::call_once<tuple<>,closure-0>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panic.rs:308
  97:     0x7ff70f941cb0 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panicking.rs:381
  98:     0x7ff70f945a07 - winit::window::{{impl}}::eq
  99:     0x7ff70f941bca - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panicking.rs:345
 100:     0x7ff70f956e46 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panic.rs:382
 101:     0x7ff70f959ea9 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
 102:     0x7ff70f95a801 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:239
 103:     0x7ff70f95b25f - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::move_state_to<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:341
 104:     0x7ff70f95a787 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::main_events_cleared<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:227
 105:     0x7ff70f988a58 - winit::platform_impl::platform::event_loop::flush_paint_messages<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:676
 106:     0x7ff70f988ff4 - winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967
 107:     0x7ff70f956d43 - std::panic::{{impl}}::call_once<isize,closure-0>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panic.rs:308
 108:     0x7ff70f941d5e - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panicking.rs:381
 109:     0x7ff70f945a07 - winit::window::{{impl}}::eq
 110:     0x7ff70f941a63 - std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panicking.rs:345
 111:     0x7ff70f956ede - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\std\src\panic.rs:382
 112:     0x7ff70f959a43 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
 113:     0x7ff70f988e11 - winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple<>>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:2151
 114:     0x7ff8e03cd3b6 - DefSubclassProc
 115:     0x7ff8e03cd26c - DefSubclassProc
 116:     0x7ff8f801e858 - CallWindowProcW
 117:     0x7ff8f801e3dc - DispatchMessageW
 118:     0x7ff8f8030bc3 - SendMessageTimeoutW
 119:     0x7ff8f944fde4 - KiUserCallbackDispatcher
 120:     0x7ff8f6b21704 - NtUserDispatchMessage
 121:     0x7ff8f801e2ea - DispatchMessageW
 122:     0x7ff70f91a816 - winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:218
 123:     0x7ff70f91ac06 - winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:188
 124:     0x7ff70f8e8cdd - winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\event_loop.rs:154
 125:     0x7ff70f8cdbcd - bevy_winit::run<closure-1>
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.4.0\src\lib.rs:121
 126:     0x7ff70f8ce179 - bevy_winit::winit_runner
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.4.0\src\lib.rs:379
 127:     0x7ff70f8ec47e - core::ops::function::Fn::call<fn(bevy_app::app::App),tuple<bevy_app::app::App>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops\function.rs:70
 128:     0x7ff7108665d5 - alloc::boxed::{{impl}}::call<tuple<bevy_app::app::App>,Fn<tuple<bevy_app::app::App>>>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\boxed.rs:1056
 129:     0x7ff71086c064 - bevy_app::app::App::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.4.0\src\app.rs:67
 130:     0x7ff710867d50 - bevy_app::app_builder::AppBuilder::run
                               at C:\Users\Anthony\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.4.0\src\app_builder.rs:49
 131:     0x7ff70ed30a9f - aeternum::main
```

**Comment by anthonyarusso** [comment]
Removed the `pub` visibility modifier from BackgroundMaterials and added `.init_resource::<BackgroundMaterials>()` to the AppBuilder within MainMenuPlugin. Removed any such initialization from main.rs. Issue is now resolved.
